remote_theme: pfgithub/cayman
custom_buttons:
  -
    title: Github
    url: https://github.com/pfgithub/shortcutslang
  -
    title: Try it
    url: https://scpl.dev
  -
    title: Getting Started
    url: https://pfgithub.github.io/shortcutslang/gettingstarted.html
